service: petabencana-twitter-replies-bot

custom:
  projectName: petabencana-twitter-replies-bot

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-1
  stackTags:
    area: Indonesia

# Add one function for each Lambda
functions:
  reply: # Lambda that gets triggered when a message is published to the SNS topic Facebook
    handler: index.main
    events:
      - sns: Twitter
