service: twitter-lambda

provider:
  name: aws
  runtime: nodejs4.3

# You can overwrite defaults by adding the following
stage: dev
region: us-east-1

# Add one function for each Lambda
functions:
  reply: # Lambda that gets triggered when a message is published to the SNS topic Facebook
    handler: handler.reply
    events:
      - sns: Twitter
